Repository oshanQQ/nyanchu-megaphone, pull requests merged in 2021-01, with the labels that each got.

#6 Tailwind CSSを導入した。
  package.json
  pages/index.tsx
  postcss.config.js
  styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: enhancement

#12 ページの大枠を作った
  pages/index.tsx
  styles/Home.module.css
  styles/globals.css
Labels: enhancement

#15 コード整形環境を整えた
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  package.json
  pages/_app.tsx
  pages/api/hello.tsx
  pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: bug, environment

#17 Reactのコンポネントが何たるかを教えてやった
  components/CenteringBox.tsx
  components/NormalButton.tsx
  components/TextField.tsx
  components/Title.tsx
  components/TweetButton.tsx
  libs/utils.ts
  pages/index.tsx
Labels: help wanted

#19 メインの機能を実装、他
  components/TextField.tsx
  pages/_app.tsx
  pages/index.tsx
Labels: bug, enhancement

#21 Fix type error
  pages/_app.tsx
Labels: bug
